#include <stdio.h>
#include "../data_encryption.h"
#include "ec_encryption.h"



//Definition of the elliptic curve, previously defined by the server so that the client can encrypt the message
#define A_PARAM 2
#define B_PARAM 2
#define P_PARAM 17

//the coordinates of the base point 
//G on the elliptic curve. The base point is used as a generator for generating other points on the curve. 
//Both the client and the server need to agree on this base point.
#define G_X_PARAM 5
#define G_Y_PARAM 1

//Number of points on the elliptic curve generated by repeatedly adding the base point to itself
#define N_PARAM 19

// Function to calculate modular inverse
int modInverse(int a, int m) {
    int m0 = m, t, q;
    int x0 = 0, x1 = 1;
    if (m == 1)
        return 0;
    while (a > 1) {
        q = a / m;
        t = m;
        m = a % m, a = t;
        t = x0;
        x0 = x1 - q * x0;
        x1 = t;
    }
    if (x1 < 0)
        x1 += m0;
    return x1;
}

// Function to add two points on the elliptic curve
Point add(Point P, Point Q, int a, int p) {

    Point R;
    int lambda;
    if (P.x == Q.x && P.y == Q.y) {
        lambda = ((3 * P.x * P.x) + a) * modInverse(2 * P.y, p) % p;
    } else {
        lambda = (Q.y - P.y) * modInverse(Q.x - P.x, p) % p;
    }
    R.x = (lambda * lambda - P.x - Q.x) % p;
    R.y = (lambda * (P.x - R.x) - P.y) % p;
    if (R.x < 0) R.x += p;
    if (R.y < 0) R.y += p;
    return R;

}

// Function to perform scalar multiplication on an elliptic curve
Point scalarMultiply(Point P, int k, int a, int p) {

    Point Q = P;
    for (int i = 1; i < k; i++) {
        Q = add(Q, P, a, p);
    }
    return Q;

}

// Elliptic curve encryption function
Point ec_encrypt(long long plaintext) {

    Point G = {G_X_PARAM, G_Y_PARAM}; // Base point
    // Calculate the numerical representation of the plaintext
    int numerical_message = plaintext;
    // Private key
    int k = numerical_message; // Using the numerical representation as private key
    // Compute R = k*G
    Point R = scalarMultiply(G, k, A_PARAM, P_PARAM);
    printf("Encrypted message point R = (%d, %d)\n", R.x, R.y);
    return R;

}
